/* 
 * Generated by construct-c (c) 2023 Alexander Kraus <nr4@z10.info>.
 * Generation timestamp: {{ info.now }}
 * Note: If you plan to edit this file, please reconsider your plan.
 */

#ifndef {{ info.nameUpperCase }}_C
#define {{ info.nameUpperCase }}_C

#ifndef {{ info.nameUpperCase }}_HEADER_ONLY
#include "{{ info.baseName }}.h"
#endif /* {{ info.nameUpperCase }}_HEADER_ONLY*/

#endif /* {{ info.nameUpperCase }}_C */
